# Generated by Django 6.0.7 on 2026-07-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('grade', models.CharField(default='A', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
